### ISSUE TITLE
Adding user tracking and stats gathering.

### ISSUE THREAD

**Issue by mgarciavaadin** [vaadin/form-filler-addon#14]
We should measure the users' numbers using our addon, we can do this with the tool created/developed mostly by Leif.
As Tarek shared this is the smaller change we could add to achieve this:
- [Changes](https://github.com/vaadin/sso-kit/blob/6bcdefac1e49e50c2f82476cc6fd6b76b19dd1a3/sso-kit-starter/src/main/java/com/vaadin/sso/starter/LicenseCheckerServiceInitListener.java#L44)
- [PR](https://github.com/vaadin/sso-kit/pull/62)

Something like this:
- ` UsageStatistics.markAsUsed(PRODUCT_NAME, version);`

A good clear **product name** would be nice to have, and **versioning** is also something to decide (starting from alpha/beta?)

**Comment by czp13** [comment]
This one as well can help:
- https://github.com/vaadin/testbench/pull/1587/files

**Comment by mgarciavaadin** [comment]
closed as duplicate #31
